### ISSUE TITLE
Step0~2 이슈 정리

### ISSUE THREAD

**Issue by zihyeon08** [devkimchi/test-container-workshop#4]
Step0
 
![image](https://github.com/user-attachments/assets/30717839-4262-43c0-bb61-469b98248ce5)

설치 확인 커맨드 후에 설치한 파일 경로가 나와야 한다고 추가 설명하면 좋을 것 같습니다. (power shell, git cli, github cli, docker desktop, visual studio code) 등등

Step 01
![image](https://github.com/user-attachments/assets/7db650bd-db42-4956-906a-62ac25642d0f)

터미널 창을 세 개 추가로 열고 새로운 터미널로 진행할 시에 test-container-workshop/workshop 위치로 이동하는 커맨드가 추가 되어있으면 더 잘 진행될 것 같습니다!

![image](https://github.com/user-attachments/assets/988476b3-9815-43f0-8964-6e58af6b0e06)

실행시에 https 막혀서 페이지 로딩이 안되는 경우 webapp을 ctrl+c 눌러서 종료하고
dotnet dev-certs https –trust 커맨드 실행후에 다시 webapp을 실행합니다.

![image](https://github.com/user-attachments/assets/3be10deb-6f0f-4682-ae83-c84a8329bb27)

‘Docker desktop을 실행한 상태로’ 실행해달라는 문구 추가하면 좋을 것 같습니다!

Compose.yaml 파일 코드에서 이름은 name: eshoplite으로 소문자만 가능하다고 오류가 납니다!! 소문자로 고치니 빌드 잘 됩니다

docker compose down –local 여기서 저는 –local 없어야 실행이 됩니다…!

Step 2
마지막 weather api 테스트 코드 작성시에 url 설정을 api/weatherforecast로 해야하는 이유가 궁금합니다!! Step 01에서는 확인할 때 항상 /weather로 해서 그대로 넣었는데 안됐었거든요..

**Comment by YoonKeumJae** [comment]
저도 `--local` 옵션을 제외한 `docker compose down` 명령어를 실행해야 잘 동작했습니다...!

**Comment by krsy0411** [comment]
<img width="622" alt="스크린샷 2024-11-29 오전 10 56 57" src="https://github.com/user-attachments/assets/9bd252d5-89d1-4c44-b28c-ec5b9e8eabea">

요건 저도 그렇네요

**Comment by krsy0411** [comment]
@zihyeon08 
`Step2 : Weather API`에서 `GET /api/weatherforecast`는 서버 api 호출 엔드포인트가 브라우저에서 표현되는 URL이랑 달라서 그런거 같아요. `eShopLite.WeatherApi`쪽에 router 매핑이 `/api/weatherforecast`로 되어있더라구요.
근데 저도 계속 `/api/weather`로 하다가 세이브포인트에는 `/api/weatherforecast`로 되어있길래 알았네용..!

**Comment by justinyoo** [comment]
> 설치 확인 커맨드 후에 설치한 파일 경로가 나와야 한다고 추가 설명하면 좋을 것 같습니다. (power shell, git cli, github cli, docker desktop, visual studio code) 등등

수정했습니다.

> 터미널 창을 세 개 추가로 열고 새로운 터미널로 진행할 시에 test-container-workshop/workshop 위치로 이동하는 커맨드가 추가 되어있으면 더 잘 진행될 것 같습니다!

수정했습니다.

> 실행시에 https 막혀서 페이지 로딩이 안되는 경우 webapp을 ctrl+c 눌러서 종료하고
> dotnet dev-certs https –trust 커맨드 실행후에 다시 webapp을 실행합니다.

이미 step-00 에서 실행시킨 명령어입니다.

> ‘Docker desktop을 실행한 상태로’ 실행해달라는 문구 추가하면 좋을 것 같습니다!

추가했습니다.

> Compose.yaml 파일 코드에서 이름은 name: eshoplite으로 소문자만 가능하다고 오류가 납니다!! 소문자로 고치니 빌드 잘 됩니다

`Compose.yaml` 파일이 아니고 `compose.yaml` 파일입니다. 그 안의 `name: eShopLite`는 굳이 대소문자를 가리지 않아요. 실제로 세이브포인트의 `compose.yaml` 파일을 열어보면 `eShopLite`라고 되어 있고, 빌드 잘 됩니다.

> docker compose down –local 여기서 저는 –local 없어야 실행이 됩니다…!

`docker compose down --rmi local`인데 오타 났습니다. 만약 이런데서 에러가 난다면 많은 경우 직접 `--help`를 붙여보면 실마리를 찾을 수 있어요.

> 마지막 weather api 테스트 코드 작성시에 url 설정을 api/weatherforecast로 해야하는 이유가 궁금합니다!! Step 01에서는 확인할 때 항상 /weather로 해서 그대로 넣었는데 안됐었거든요..

step-01 문서의 첫부분에서 API 엔드포인트가 `/api/weatherforecast`라고 했습니다. `/weather`는 웹앱의 페이지 링크예요.
