### ISSUE TITLE
[Step 3] 테스트 코드 작성 : Web App

### ISSUE THREAD

**Issue by krsy0411** [devkimchi/test-container-workshop#6]
저스틴님 의도대로 문서가 적힌게 맞는건지 제가 생각하는 게 맞는지는 모르겠는데, 우선 적어두겠습니다.
제가 이상하다고 생각되는 부분이 아래 사진인데요.

<img width="1135" alt="스크린샷 2024-11-29 오후 6 40 45" src="https://github.com/user-attachments/assets/388f65fd-ddce-46fa-812d-8951831c672c">

**파일 경로가 폴더 경로랑 달라서** 세이브 포인트(`step-03`)를 확인해보니까 `eShopLite.WebApp.Tests/Components/Pages/`내에 테스트 파일들이 작성되어있더라구요(명령어 그대로 복붙하면 실제로 파일이 경로를 못 찾는다는 에러 문구를 보여줍니다).

그래서 저스틴님 의도랑 다른게 맞다면, touch 명령어에 대한 경로를 `test/eShopLite.WebApp.Tests/Components/Pages/ProductsPageTests/cs`로 수정하셔야할 것 같습니다(2번 경로도 수정하셔야할 거 같아요).

**Comment by krsy0411** [comment]
경로 그대로 사용하면 나오는 에러 내용입니다.

<img width="1063" alt="스크린샷 2024-11-29 오후 6 49 34" src="https://github.com/user-attachments/assets/06a810c6-c27a-4997-9199-043deb7d17b0">

**Comment by justinyoo** [comment]
오탈자 수정했습니다!
