### ISSUE TITLE
[STEP 01] 기본 프로젝트 빌드 및 실행

### ISSUE THREAD

**Issue by krsy0411** [devkimchi/test-container-workshop#8]
아래 사진에서 터미널 창 3개를 더 띄울 때, 
<img width="1126" alt="스크린샷 2024-12-08 오전 9 32 43" src="https://github.com/user-attachments/assets/82ac9d4e-c148-44b4-93b1-f51294a8965d">

아래 사진처럼 $REPOSITORY_ROOT를 인식하지 못합니다.
<img width="1088" alt="스크린샷 2024-12-08 오전 9 33 54" src="https://github.com/user-attachments/assets/6ed8aa9f-38b6-4a98-88de-0a45b992fefe">

아래 명령어들을 각 터미널마다 입력해달라는 이야기를 해주시는건 어떨까요??
<img width="1078" alt="스크린샷 2024-12-08 오전 9 35 20" src="https://github.com/user-attachments/assets/5501d12f-6aae-452c-8b99-856721cb073d">
<img width="1078" alt="스크린샷 2024-12-08 오전 9 36 08" src="https://github.com/user-attachments/assets/6fd3d672-c4ad-46e7-aa8d-bbba6239c385">

> 혹시나 싶어서 이슈 남겼습니다(왜 저번엔 몰랐지..)
@justinyoo

**Comment by justinyoo** [comment]
아 맞네... 터미널 열면 세션이 다 따로여서 새로 해야 하겠네요 ㄷㄷㄷ
